In [18]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from glob import glob
from scipy.optimize import curve_fit

In [22]:
exps = ['GramA 2.6nM','GramA 260pM20210920','GUV','OmpF_20210421','OmpF_20210427']
path_identifier = ['3nM','260pM20210920','GUV','OmpF_20210421','OmpF_20210427']

paths = np.array(glob('Permeabilities*.csv'))
print(paths)
exp_hash = {}
positions = np.arange(len(paths))

for i,path_id in enumerate(path_identifier):
    for position,path in enumerate(paths[positions]):
        if path.find(path_id) != -1:
            
            exp_hash[exps[i]] = path
#             positions = np.concatenate((positions[:position],positions[position+1:]))
            print(positions)

['Permeabilities_GramicidinA_260pM20210920.csv'
 'Permeabilities_OmpF_20210421.csv'
 'Permeabilities_GramicidinA_3nM_20210920.csv'
 'Permeabilities_OmpF_20210427.csv' 'Permeabilities_GUV.csv']
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


In [23]:
exp_hash

{'GramA 2.6nM': 'Permeabilities_GramicidinA_3nM_20210920.csv',
 'GramA 260pM20210920': 'Permeabilities_GramicidinA_260pM20210920.csv',
 'GUV': 'Permeabilities_GUV.csv',
 'OmpF_20210421': 'Permeabilities_OmpF_20210421.csv',
 'OmpF_20210427': 'Permeabilities_OmpF_20210427.csv'}

In [23]:

dfs = {exps[i]: pd.read_csv(exp_hash[exps[i]]) for i in range(len(exps))}

In [12]:
%matplotlib qt
fig, axs  = plt.subplots(1,len(dfs.keys()))

rel_err_threshold = 0.15
for i,key in enumerate(dfs.keys()):
    
    rel_err = dfs[key]['dP/P'].to_numpy().astype(float)
    P = dfs[key]['P cms^-1'].to_numpy().astype(float)
    rel_err = rel_err[P > 0]
    P = P[P > 0]

    
    axs[i].hist(np.log10(P[rel_err < rel_err_threshold ]),'sturges')
    
    x_lab = [-8,-6.5,-5]
    y_lab = [0,5,10]
    
    axs[i].set_xticks(x_lab)
    axs[i].set_xticklabels(x_lab,fontsize = 15)
    
    axs[i].set_yticks(y_lab)
    axs[i].set_yticklabels(y_lab,fontsize = 15)
    
    axs[i].set_xlim([-8.5,-4.5])
    axs[i].set_ylim([0,11])
    
    axs[i].set_title(key)

In [13]:
print(plt.rcParams['axes.prop_cycle'].by_key()['color'])

['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']


In [14]:
root = 'OmpF'

def get_repeats(root,exps):
    repeat_keys = []
    
    for exp in exps:
        if exp.find(root) != -1:
            repeat_keys.append(exp)
            
    return repeat_keys

repeats = get_repeats(root,exps)

In [15]:
dfs['OmpF'] = pd.concat([dfs[key] for key in repeats])

In [16]:
dfs['OmpF']

Unnamed: 0       P ms^-1      dP/P           A      P cms^-1
0            0  1.893709e-10  0.471447  164.133333  1.893709e-08
1            1  2.739703e-09  0.023799  204.233333  2.739703e-07
2            2  4.235137e-09  0.024887   93.466667  4.235137e-07
3            3  1.068535e-08  0.030345  180.833333  1.068535e-06
4            4  1.906911e-09  0.036093  149.433333  1.906911e-07
5            5  5.944139e-09  0.018338  216.966667  5.944139e-07
6            6  2.126354e-09  0.025744  178.333333  2.126354e-07
7            7  2.209157e-09  0.038625  246.966667  2.209157e-07
8            8  1.840337e-09  0.023493  212.266667  1.840337e-07
9            9  4.140656e-09  0.018927  176.166667  4.140656e-07
10          10  3.343073e-09  0.018788  166.666667  3.343073e-07
11          11  1.460283e-09  0.033412  192.933333  1.460283e-07
12          12  4.218798e-09  0.016513  210.933333  4.218798e-07
13          13  3.053117e-09  0.032279  200.566667  3.053117e-07
14          14  1.917609e-09  0.050271  166.166667  1.917609e-07
15          15  4.385263e-09  0.019533  164.800000  4.385263e-07
16          16  8.733433e-10  0.062055  168.133333  8.733433e-08
17          17  1.380432e-09  0.032159  184.433333  1.380432e-07
18          18  3.043838e-09  0.030689  171.600000  3.043838e-07
19          19  1.428471e-10  0.842212  193.466667  1.428471e-08
20          20  4.912977e-09  0.026212  167.066667  4.912977e-07
21          21  2.467199e-09  0.032913  211.366667  2.467199e-07
22          22  9.993784e-10  0.081197  188.166667  9.993784e-08
23          23  2.486719e-09  0.054046  166.800000  2.486719e-07
24          24  3.302833e-09  0.013929  126.733333  3.302833e-07
25          25  1.263129e-10  0.310010  147.033333  1.263129e-08
26          26  1.113221e-09  0.052136  253.233333  1.113221e-07
27          27  7.858897e-09  0.034005  184.666667  7.858897e-07
28          28  1.430660e-09  0.060641  201.566667  1.430660e-07
29          29  2.727619e-09  0.037577  196.166667  2.727619e-07
..         ...           ...       ...         ...           ...
31          31  9.885377e-09  0.115804  244.700000  9.885377e-07
32          32  1.328507e-08  0.120987  208.766667  1.328507e-06
33          33  1.034965e-08  0.118312  233.866667  1.034965e-06
34          34  1.861972e-08  0.130894  175.766667  1.861972e-06
35          35  8.889083e-09  0.120494  238.933333  8.889083e-07
36          36  1.063004e-08  0.121734  180.800000  1.063004e-06
37          37  1.359070e-08  0.135073  179.233333  1.359070e-06
38          38  4.428601e-09  0.120541  234.166667  4.428601e-07
39          39  9.317761e-09  0.122497  149.933333  9.317761e-07
40          40  5.301046e-09  0.109803  149.066667  5.301046e-07
41          41  3.564199e-09  0.144796   97.366667  3.564199e-07
42          42  1.037693e-08  0.154651  160.366667  1.037693e-06
43          43  1.048221e-08  0.185170  201.666667  1.048221e-06
44          44  1.145007e-08  0.148750  167.066667  1.145007e-06
45          45  1.141490e-08  0.163299  165.633333  1.141490e-06
46          46  9.508567e-09  0.147721  268.033333  9.508567e-07
47          47  9.885749e-09  0.156952  200.266667  9.885749e-07
48          48  8.097511e-09  0.132630  262.600000  8.097511e-07
49          49  1.017905e-08  0.150586  133.633333  1.017905e-06
50          50  2.275373e-09  0.247142  166.866667  2.275373e-07
51          51  1.438377e-08  0.126080  183.700000  1.438377e-06
52          52  5.925501e-09  0.120996  119.733333  5.925501e-07
53          53  8.305107e-09  0.137326  177.700000  8.305107e-07
54          54  1.413846e-08  0.134057  255.766667  1.413846e-06
55          55  1.255154e-08  0.142738  197.433333  1.255154e-06
56          56  1.191624e-08  0.129759  192.800000  1.191624e-06
57          57  1.577004e-08  0.127496  207.600000  1.577004e-06
58          58  6.114814e-09  0.122535  160.566667  6.114814e-07
59          59  5.564177e-09  0.161673  155.300000  5.564177e-07
60          60  3.695202e-09  0.156059 

In [24]:
# now when happy with the settings arrange on one plot
fig, ax  = plt.subplots(1,1)

rel_err_threshold = 0.15
bins = {'GramA 2.6nM': 8, 'GramA 260pM20210920': 5,'GUV':12,'OmpF':9,'OmpF_20210421':6,'OmpF_20210427':6,'OmpF':9}
for i,key in enumerate(bins.keys()):
    if key not in ['GUV','OmpF_20210427']:
        continue
    rel_err = dfs[key]['dP/P'].to_numpy().astype(float)
    P = dfs[key]['P cms^-1'].to_numpy().astype(float)
    rel_err = rel_err[P > 0]
    P = P[P > 0]

    color = plt.rcParams['axes.prop_cycle'].by_key()['color'][i]
    if i == 2:
        color = 'g'
    if i == 5:
        color = 'C1'
    ax.hist(np.log10(P[rel_err < rel_err_threshold]),bins[key],label = key,alpha = 0.3,color = color,
            edgecolor = color)
    
x_lab = [-8,-6.5,-5]
y_lab = [0,10,20]

ax.set_xticks(x_lab)
ax.set_xticklabels(x_lab,fontsize = 15)

ax.set_yticks(y_lab)
ax.set_yticklabels(y_lab,fontsize = 15)

ax.set_xlim([-8.5,-4.5])
ax.set_ylim([0,20])

# ax.set_title(key)

ax.set_xlabel('$Log_{10} (P [cms^{-1}])$',fontsize = 18)
ax.set_ylabel('# GUVs',fontsize = 18)
# plt.legend()

plt.tick_params(direction = 'in',top= True, right = True,left = True, bottom = True, length = 6)


In [29]:
# now when happy with the settings arrange on one plot
fig, ax  = plt.subplots(1,1)

rel_err_threshold = 0.15
bins = {'GramA 2.6nM': 8, 'GramA 260pM20210920': 5,'GUV':12,'OmpF':9,'OmpF_20210421':6,'OmpF_20210427':4,'OmpF':9}
for i,key in enumerate(bins.keys()):
    if key not in ['OmpF_20210421','OmpF_20210427']:
        continue
    rel_err = dfs[key]['dP/P'].to_numpy().astype(float)
    P = dfs[key]['P cms^-1'].to_numpy().astype(float)
    rel_err = rel_err[P > 0]
    P = P[P > 0]

    color = plt.rcParams['axes.prop_cycle'].by_key()['color'][i]
    if i == 5:
        color = 'C0'
    if i == 4:
        color = 'C1'
    ax.hist(np.log10(P[rel_err < rel_err_threshold]),bins[key],label = key,alpha = 0.3,color = color,
            edgecolor = color)
    
x_lab = [-8,-6.5,-5]
y_lab = [0,10,20]

ax.set_xticks(x_lab)
ax.set_xticklabels(x_lab,fontsize = 28)

ax.set_yticks(y_lab)
ax.set_yticklabels(y_lab,fontsize = 28)

ax.set_xlim([-8.5,-4.5])
ax.set_ylim([0,20])

# ax.set_title(key)

ax.set_xlabel('$Log_{10} (P [cms^{-1}])$',fontsize = 30)
ax.set_ylabel('# GUVs',fontsize = 30)
# plt.legend()

plt.tick_params(direction = 'in',top= True, right = True,left = True, bottom = True, length = 6)


In [27]:
# now when happy with the settings arrange on one plot
fig, ax  = plt.subplots(1,1)

bins = {'GramA 2.6nM': 9, 'GramA 260pM20210920': 5,'GUV':8,'OmpF':6}
for i,key in enumerate(dfs.keys()):
    print(key)
    if key not in ['GramA 2.6nM','GramA 260pM20210920']:
        continue
    rel_err = dfs[key]['dP/P'].to_numpy().astype(float)
    P = dfs[key]['P cms^-1'].to_numpy().astype(float)
    rel_err = rel_err[P > 0]
    P = P[P > 0]

    color = plt.rcParams['axes.prop_cycle'].by_key()['color'][i]
    
    ax.hist(np.log10(P[rel_err < 0.1]),bins[key],label = key,alpha = 0.3,
            edgecolor = color)
    
x_lab = [-7,-6.5,-6]
y_lab = [0,10,20,30]

ax.set_xticks(x_lab)
ax.set_xticklabels(x_lab,fontsize = 22)

ax.set_yticks(y_lab)
ax.set_yticklabels(y_lab,fontsize = 22)

ax.set_xlim([-7.5,-5.5])
ax.set_ylim([0,31])

# ax.set_title(key)

ax.set_xlabel('$Log_{10} (P [cms^{-1}])$',fontsize = 25)
ax.set_ylabel('# GUVs',fontsize = 25)
# plt.legend(

plt.tick_params(direction = 'in',top= True, right = True,left = True, bottom = True, length = 6)


GramA 2.6nM
GramA 260pM20210920
GUV
OmpF_20210421
OmpF_20210427


# Fit conductance vs concentration for OmpF


In [70]:
dfGvsK = pd.DataFrame({'[K][molm^-3]': np.array([250,500,750,1000]),'G [S]':1.07*(1e-3)*(1e-9)*np.array([250,500,750,1000])+0.22*1e-9})

In [71]:
# fitting function

def GfromC(C,P):
    F = 96485
    R = 8.31
    T = 298
    
    return (F**2*C*P)/(R*T)

guess = [2e-18]

# fit using curve fitabs
params = curve_fit(GfromC,dfGvsK['[K][molm^-3]'],dfGvsK['G [S]'],p0 = guess)

In [72]:
fig, ax = plt.subplots(1,1)

ax.scatter(dfGvsK['[K][molm^-3]'],dfGvsK['G [S]'])


In [73]:
params

(array([3.62660068e-19]), array([[4.05907377e-40]]))

In [74]:
#{ key: [Conductance,Potassium concentration when measured]}

conductances = {'OmpF':[8e-10,100],'GramA':[1.4e-11,100]}


def PfromG(G,C,R = 8.31,T = 298,F = 96485):
    #make sure C is given as molm^-3 for units to make sense
    #also G given as Siemens (Amperes/Volts)
    
    #returns P in m^3/s
    return G*(R*T)/(F**2*C)
   
    
    
exp_one_P = {key: PfromG(*conductances[key]) for key in conductances.keys()}

In [76]:
# use fit for permeability of one OmpF pore
exp_one_P['OmpF'] = params[0]
exp_one_P['OmpF_20210427'] = params[0]
exp_one_P['OmpF_20210421'] = params[0]

In [41]:
exp_one_P

{'OmpF': 2.128078639302326e-18,
 'GramA': 3.724137618779071e-20,
 'OmpF_20210427': array([1.01743076e-18]),
 'OmpF_20210421': array([1.01743076e-18])}

In [77]:
App = 3.16 #um^2
for key in exps+['OmpF']:
    
    if key in ['GUV','GramA 2.6nM', 'GramA 260pM20210920']:
        continue
        
    if key.find('GramA') != -1:
        id_ = 'GramA'
        
#     if key in ['OmpF_20210421','OmpF_20210427']:
#         id_ = 'OmpF'
    else:
        id_  = key
        
    dfs[key]['P1_exp ms^-1'] = exp_one_P[id_]/(dfs[key]['A']*App*1e-12)
    dfs[key]['N'] = dfs[key]['P ms^-1']/dfs[key]['P1_exp ms^-1']

In [43]:
dfs['OmpF_20210421']

Unnamed: 0       P ms^-1      dP/P           A      P cms^-1  \
0            0  1.893709e-10  0.471447  164.133333  1.893709e-08   
1            1  2.739703e-09  0.023799  204.233333  2.739703e-07   
2            2  4.235137e-09  0.024887   93.466667  4.235137e-07   
3            3  1.068535e-08  0.030345  180.833333  1.068535e-06   
4            4  1.906911e-09  0.036093  149.433333  1.906911e-07   
5            5  5.944139e-09  0.018338  216.966667  5.944139e-07   
6            6  2.126354e-09  0.025744  178.333333  2.126354e-07   
7            7  2.209157e-09  0.038625  246.966667  2.209157e-07   
8            8  1.840337e-09  0.023493  212.266667  1.840337e-07   
9            9  4.140656e-09  0.018927  176.166667  4.140656e-07   
10          10  3.343073e-09  0.018788  166.666667  3.343073e-07   
11          11  1.460283e-09  0.033412  192.933333  1.460283e-07   
12          12  4.218798e-09  0.016513  210.933333  4.218798e-07   
13          13  3.053117e-09  0.032279  200.566667  3.053117e-07   
14          14  1.917609e-09  0.050271  166.166667  1.917609e-07   
15          15  4.385263e-09  0.019533  164.800000  4.385263e-07   
16          16  8.733433e-10  0.062055  168.133333  8.733433e-08   
17          17  1.380432e-09  0.032159  184.433333  1.380432e-07   
18          18  3.043838e-09  0.030689  171.600000  3.043838e-07   
19          19  1.428471e-10  0.842212  193.466667  1.428471e-08   
20          20  4.912977e-09  0.026212  167.066667  4.912977e-07   
21          21  2.467199e-09  0.032913  211.366667  2.467199e-07   
22          22  9.993784e-10  0.081197  188.166667  9.993784e-08   
23          23  2.486719e-09  0.054046  166.800000  2.486719e-07   
24          24  3.302833e-09  0.013929  126.733333  3.302833e-07   
25          25  1.263129e-10  0.310010  147.033333  1.263129e-08   
26          26  1.113221e-09  0.052136  253.233333  1.113221e-07   
27          27  7.858897e-09  0.034005  184.666667  7.858897e-07   
28          28  1.430660e-09  0.060641  201.566667  1.430660e-07   
29          29  2.727619e-09  0.037577  196.166667  2.727619e-07   
30          30  3.742659e-09  0.015166  229.166667  3.742659e-07   
31          31  4.893944e-09  0.025883   97.466667  4.893944e-07   
32          32  1.043020e-08  0.029971  181.766667  1.043020e-06   
33          33  2.443578e-09  0.033716  252.300000  2.443578e-07   
34          34  1.931156e-09  0.030425  220.000000  1.931156e-07   
35          35  4.205035e-09  0.018008  187.800000  4.205035e-07   

    P1_exp ms^-1         N  
0   4.103022e-09  0.046154  
1   3.297418e-09  0.830863  
2   7.205163e-09  0.587792  
3   3.724107e-09  2.869239  
4   4.506642e-09  0.423134  
5   3.103899e-09  1.915056  
6   3.776314e-09  0.563077  
7   2.726856e-09  0.810148  
8   3.172625e-09  0.580067  
9   3.822758e-09  1.083159  
10  4.040656e-09  0.827359  
11  3.490546e-09  0.418354  
12  3.192680e-09  1.321397  
13  3.357700e-09  0.909288  
14  4.052814e-09  0.473155  
15  4.086424e-09  1.073130  
16  4.005408e-09  0.218041  
17  3.651415e-09  0.378054  
18  3.924491e-09  0.775601  
19  3.480923e-09  0.041037  
20  4.030981e-09  1.218804  
21  3.186134e-09  0.774355  
22  3.578969e-09  0.279236  
23  4.037426e-09  0.615917  
24  5.313855e-09  0.621551  
25  4.580204e-09  0.027578  
26  2.659376e-09  0.418602  
27  3.646801e-09  2.155011  
28  3.341042e-09  0.428208  
29  3.433012e-09  0.794526  
30  2.938659e-09  1.273595  
31  6.909466e-09  0.708296  
32  3.704984e-09  2.815180  
33  2.669214e-09  0.915467  
34  3.061103e-09  0.630869  
35  3.585956e-09  1.172640

In [78]:
# process Number of pores per GUV to m#ake sense
key = 'OmpF'

for key in ['OmpF_20210427','OmpF_20210421']:
    dfs[key]['N'].iloc[dfs[key]['N'].to_numpy().astype(float) < 1] = 0

/home/marcus/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [79]:
for key in dfs.keys():
    if key =='GUV':
        continue
    print(key,dfs[key]['N'])

GramA 2.6nM 0        41.980475
1       212.589587
2        60.640318
3      1529.590792
4      5589.707882
5      3504.251849
6         9.837165
7      4500.570928
8       121.309855
9      1867.116107
10      223.030662
11      118.278106
12      372.887843
13      769.834387
14      199.584774
15       52.022997
16      257.154067
17     1206.441703
18      436.157227
19       91.494877
20      548.589549
21       69.665624
22      104.559905
23      131.816137
24      303.362955
25       95.059934
26      366.755697
27      448.710889
28      241.760507
29     3846.414216
          ...     
75     4491.965770
76       97.894319
77      181.133183
78      307.115152
79      685.823012
80     6885.508469
81      438.266537
82      561.506966
83      305.038353
84       95.499310
85      236.772214
86       58.830394
87       23.576106
88      140.859762
89      263.660242
90      361.036613
91      211.278312
92      303.463786
93      294.031375
94     1403.776496
95     1642.532687


In [45]:
%matplotlib qt
fig, axs  = plt.subplots(1,len(dfs.keys()))

for i,key in enumerate(dfs.keys()):
    
    if key == 'GUV':
        continue
    rel_err = dfs[key]['dP/P'].to_numpy().astype(float)
    N = dfs[key]['N'].to_numpy().astype(float)
    rel_err = rel_err[N > 0]
    N = N[N > 0]

    if key == 'OmpF':
        axs[i].hist(N[rel_err < 0.2],'sqrt')
        
    else:
        axs[i].hist(np.log10(N[rel_err < 0.1]),'sqrt')
    axs[i].set_title(key)

In [37]:
# Gramicidin A plot

keys = ['GramA 2.6nM','GramA 260pM20210920']

fig, ax = plt.subplots(1,1)


for i,key in enumerate(keys):

    rel_err = dfs[key]['dP/P'].to_numpy().astype(float)
    N = dfs[key]['N'].to_numpy().astype(float)
    
    color = plt.rcParams['axes.prop_cycle'].by_key()['color'][i]
    ax.hist(np.log10(N[rel_err < 0.1]),5,label = key,alpha = 0.3,
            edgecolor = color)
    

x_ticks = [2,3,4]
y_ticks= [0,10,20,30]

  
plt.tick_params(direction = 'in',top= True, right = True,left = True, bottom = True, length = 6)

ax.set_xticks(x_ticks)
ax.set_xticklabels(x_ticks,fontsize = 15)
ax.set_yticks(y_ticks)
ax.set_yticklabels(y_ticks,fontsize = 15)

ax.set_ylabel('# GUVs',fontsize = 18)
ax.set_xlabel('$Log_{10}$(No. of pores per GUV)', fontsize = 18)

ax.set_xlim([1.9,4.1])
# plt.legend()


(1.9, 4.1)

In [61]:
N

array([ 0.09653665,  1.73785013,  1.22943752,  6.00135748,  0.88503457,
        4.00556881,  1.1777426 ,  1.69452209,  1.21328082,  2.26555741,
        1.73052101,  0.87503697,  2.76386057,  1.90188598,  0.98966058,
        2.24457967,  0.45605899,  0.79074552,  1.62226232,  0.08583411,
        2.54927541,  1.61965639,  0.58405654,  1.28826411,  1.30004876,
        0.05768272,  0.87555677,  4.50746451,  0.89564771,  1.66184745,
        2.66387588,  1.48148523,  5.88828779,  1.91480981,  1.31953875,
        2.45271691,  5.24591526,  9.15368117,  4.55236743, 10.45624893,
        5.26111065, 31.7530412 ,  3.9856635 , 11.76127302,  9.78288509,
       10.50082153, 11.57644842, 14.34430673, 18.07009712,  4.91212587,
       17.9414483 ,  7.78999729,  7.62652669,  7.32558652,  7.76115231,
        9.78374951,  7.78103049,  9.44638387, 14.73786868,  7.83104983,
        6.93396476,  9.02689842,  9.3880905 ,  8.30364905, 10.71345003,
       10.03450483, 10.28374369, 13.34231682,  8.76915427,  6.10

In [81]:
# OmpF plot
keys = ['OmpF_20210427','OmpF_20210421']

fig, ax = plt.subplots(1,1)

bins = {'GramA 2.6nM': 8, 'GramA 260pM20210920': 5,'GUV':12,'OmpF':9,'OmpF_20210421':6,'OmpF_20210427':13,'OmpF':9}
for i,key in enumerate(keys):

    rel_err = dfs[key]['dP/P'].to_numpy().astype(float)
    N = dfs[key]['N'].to_numpy().astype(float)
    
    color = plt.rcParams['axes.prop_cycle'].by_key()['color'][i]
    ax.hist(N[rel_err < rel_err_threshold],bins[key],label = key,alpha = 0.3,color = 'C'+str(i),
            edgecolor = 'C'+str(i))
    

x_ticks = [0,25,50]
y_ticks= [0,8,16]

  
plt.tick_params(direction = 'in',top= True, right = True,left = True, bottom = True, length = 6)

ax.set_xticks(x_ticks)
ax.set_xticklabels(x_ticks,fontsize = 15)
ax.set_yticks(y_ticks)
ax.set_yticklabels(y_ticks,fontsize = 15)

ax.set_ylabel('# GUVs',fontsize = 18)
ax.set_xlabel('$No. of pores per GUV', fontsize = 18)

# ax.set_xlim([1.9,4.1])
# plt.legend()
# 

Text(0.5, 0, '$No. of pores per GUV')